INP_DIR = '../sample' # the input directory containing the video and gaze signal
OUT_DIR = INP_DIR+'/res'
CLOUD_FORMAT = False
VIDEO_SIZE = [1088, 1080]  # [width, height]
GAZE_ERROR = [17, 0] # [x, y]
# PATCH_SIZE = 100
PATCH_SIZE = 64
VISUALIZE = True
PATCH_DIST_THRESH = 0.2
GAZE_DIST_THRESH = 2.5
ENV_CHANGE_THRESH = 3